spring:
  application:
    name: ReadingTrackerWebApp
  h2:
    console:
      path: /my-h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/books
    username: darynavlasiuk
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true:
  sql:
    init:
      data-locations: classpath:data/data.sql
      mode: never